name: Main workflow 
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: AutoRebase Step
      uses: ./
      with:
        label: autorebase
      env: 
        token: ${{ secrets.GIT_TOKEN }}  
