name: Main workflow 
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: ./
      with:
        label: autorebase
