name: Main workflow 
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: npm ci
    - uses: npm test
    - uses: npm run build
    - uses: ./
      with:
        label: autorebase
